"""Settings: CLI flags and ``TAPDROP_*`` environment variables.

Every flag in the CLI contract has an env var with the same name in upper snake
case. The precedence is the usual one for pydantic-settings: explicit CLI value,
then environment, then the default in the table in ``RDD.md``.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Annotated

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict

_DURATION_RE = re.compile(r"^\s*(\d+(?:\.\d+)?)\s*([smhdw])\s*$", re.IGNORECASE)

_DURATION_UNITS = {
    "s": 1.0,
    "m": 60.0,
    "h": 3600.0,
    "d": 86400.0,
    "w": 604800.0,
}


def parse_duration(value: str) -> timedelta:
    """Parse a TTL string such as ``2h``, ``24h``, ``7d`` into a timedelta.

    A bare number is read as seconds so ``--ttl 30`` behaves sensibly, and the
    2 s TTL used by the shutdown test stays expressible.
    """
    text = value.strip()
    if not text:
        raise ValueError("Duration is empty.")
    if re.fullmatch(r"\d+(?:\.\d+)?", text):
        return timedelta(seconds=float(text))
    match = _DURATION_RE.match(text)
    if match is None:
        raise ValueError(f"Cannot parse duration {value!r}. Use forms like 30s, 15m, 2h, 7d.")
    amount, unit = match.groups()
    seconds = float(amount) * _DURATION_UNITS[unit.lower()]
    if seconds <= 0:
        raise ValueError(f"Duration {value!r} must be positive.")
    return timedelta(seconds=seconds)


def _split_uris(value: str | list[str] | None) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [item for item in value if item]
    return [part.strip() for part in value.split(",") if part.strip()]


class Settings(BaseSettings):
    """Runtime configuration for one ``tapdrop serve`` process."""

    model_config = SettingsConfigDict(
        env_prefix="TAPDROP_",
        extra="ignore",
        case_sensitive=False,
    )

    # NoDecode keeps pydantic-settings from JSON-parsing these env vars, so
    # TAPDROP_SOURCES stays a plain comma-separated list rather than a JSON array.
    sources: Annotated[list[str], NoDecode] = Field(default_factory=list)
    images: Annotated[list[str], NoDecode] = Field(default_factory=list)

    host: str = "127.0.0.1"
    port: int = 8000

    ttl: str | None = None
    share: bool = False
    token: str | None = None
    allow_upload: bool = False

    config_file: Path | None = None
    result_store: str = "~/.cache/tapdrop/results"

    max_rows: int = 100_000
    hard_max_rows: int = 10_000_000
    query_timeout: int = 300
    async_query_timeout: int = 3600
    max_jobs: int = 4
    memory_limit: str = "75%"
    upload_max_mb: int = 200

    cache: bool = False
    log_dir: Path | None = None
    public_url: str | None = None

    # Set at startup once the TTL is resolved; surfaced as VOSI <downAt>.
    down_at: datetime | None = None

    @field_validator("sources", "images", mode="before")
    @classmethod
    def _coerce_uri_list(cls, value: str | list[str] | None) -> list[str]:
        return _split_uris(value)

    @field_validator("ttl")
    @classmethod
    def _validate_ttl(cls, value: str | None) -> str | None:
        if value is not None:
            parse_duration(value)  # raises on a malformed duration at startup, not mid-request
        return value

    @field_validator("hard_max_rows")
    @classmethod
    def _hard_max_is_a_ceiling(cls, value: int) -> int:
        if value <= 0:
            raise ValueError("hard_max_rows must be positive.")
        return value

    @property
    def ttl_delta(self) -> timedelta | None:
        return parse_duration(self.ttl) if self.ttl else None

    def resolve_down_at(self, now: datetime | None = None) -> datetime | None:
        """Compute the expiry instant, defaulting to 24 h when ``--share`` is set.

        A shared service is publicly reachable, so it always expires even if the
        publisher forgot ``--ttl``.
        """
        delta = self.ttl_delta
        if delta is None and self.share:
            delta = timedelta(hours=24)
        if delta is None:
            return None
        return (now or datetime.now(UTC)) + delta

    @property
    def result_store_path(self) -> Path | None:
        """Local result directory, or ``None`` when results go to S3."""
        if self.result_store.startswith("s3://"):
            return None
        return Path(self.result_store).expanduser()

    @property
    def preview_cache_path(self) -> Path:
        """Where generated PNG previews are cached (RDD.md M10).

        Derived from ``--result-store`` rather than getting a flag of its own:
        both are caches of generated bytes, and a flag would need a matching
        ``TAPDROP_*`` variable for something a user has no reason to move.

        AIDEV-NOTE: this sits *inside* the result store, not beside it. The
        parent of a store like ``/tmp/results`` is world-writable, so a
        predictable ``/tmp/previews`` could be pre-created (or symlinked
        elsewhere) by another user before tapdrop starts.
        """
        local = self.result_store_path
        base = local if local is not None else Path("~/.cache/tapdrop").expanduser()
        return base / "previews"

    @property
    def root_path(self) -> str:
        """Service root: ``/`` or the secret ``/t/<token>`` prefix."""
        return f"/t/{self.token}" if self.token else ""

    def effective_maxrec(self, requested: int | None) -> int:
        """Clamp a client ``MAXREC`` to the configured ceiling.

        ``MAXREC=0`` is legal in TAP and means metadata only, so it is preserved
        rather than treated as "unset".
        """
        if requested is None:
            return self.max_rows
        if requested < 0:
            raise ValueError("MAXREC must not be negative.")
        return min(requested, self.hard_max_rows)
